server:
  port: 0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:7080/realms/common-ground

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  keycloak:
    admin:
      clientId: common-ground-spring-id
      clientSecret: UDWnGW0PQUQCyBSTzVs6uLJIT4XhmJG9
    realm: common-ground
    serverUrl: http://localhost:7080